Create or replace table PH_DATA.NORTHWOODS.CANCEL_REASON_CODE

(
cancel_code VARCHAR(500) not null,
CANCELLATION_REASON VARCHAR,
CONSTRAINT PK_CANCEL_REASON_CODE_KEY PRIMARY KEY (cancel_code)
);

create or replace  TABLE PH_DATA.NORTHWOODS.AIRPORTS (
	IATA_CODE VARCHAR(16777216) NOT NULL,
	AIRPORT VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
    CONSTRAINT PK_AIRPORTS_KEY PRIMARY KEY (IATA_CODE)
);

create  TABLE PH_DATA.NORTHWOODS.AIRLINES ( 	
AIRLINE VARCHAR(16777216) , 	
IATA_CODE VARCHAR(16777216) NOT NULL,
CONSTRAINT PK_AIRLINES_KEY PRIMARY KEY (IATA_CODE)
);


---
Create  table PH_DATA.NORTHWOODS.FLIGHTS
cluster by LINEAR(YEAR,MONTH)
(
YEAR NUMBER(38,0) NOT NULL,
	MONTH NUMBER(38,0) NOT NULL,
	DAY NUMBER(38,0) NOT NULL,
	DAY_OF_WEEK NUMBER(38,0),
	AIRLINE VARCHAR(16777216) NOT NULL,
	FLIGHT_NUMBER VARCHAR(16777216) NOT NULL,
	TAIL_NUMBER VARCHAR(16777216),
	ORIGIN_AIRPORT VARCHAR(16777216) NOT NULL,
	DESTINATION_AIRPORT VARCHAR(16777216) NOT NULL,
	SCHEDULED_DEPARTURE VARCHAR(16777216),
	DEPARTURE_TIME VARCHAR(16777216),
	DEPARTURE_DELAY NUMBER(38,0),
	TAXI_OUT NUMBER(38,0),
	WHEELS_OFF VARCHAR(16777216),
	SCHEDULED_TIME NUMBER(38,0),
	ELAPSED_TIME NUMBER(38,0),
	AIR_TIME NUMBER(38,0),
	DISTANCE NUMBER(38,0),
	WHEELS_ON NUMBER(38,0),
	TAXI_IN NUMBER(38,0),
	SCHEDULED_ARRIVAL NUMBER(38,0),
	ARRIVAL_TIME VARCHAR(16777216),
	ARRIVAL_DELAY VARCHAR(16777216),
	DIVERTED NUMBER(38,0),
	CANCELLED NUMBER(38,0),
	CANCELLATION_REASON VARCHAR(16777216),
	AIR_SYSTEM_DELAY NUMBER(38,0),
	SECURITY_DELAY NUMBER(38,0),
	AIRLINE_DELAY NUMBER(38,0),
	LATE_AIRCRAFT_DELAY NUMBER(38,0),
	WEATHER_DELAY NUMBER(38,0),
    CONSTRAINT PK_FLIGHTS_KEY PRIMARY KEY (YEAR,
                                            MONTH,
                                            DAY,
                                            FLIGHT_NUMBER,
                                            AIRLINE,
                                            ORIGIN_AIRPORT,
                                            DESTINATION_AIRPORT)
    , CONSTRAINT FK_FLIGHTS_KEY_AIRLINE FOREIGN KEY (AIRLINE) REFERENCES PH_DATA.NORTHWOODS.AIRLINES(IATA_CODE)
    , CONSTRAINT FK_FLIGHTS_KEY_ORIGIN_AIRPORTS FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES PH_DATA.NORTHWOODS.AIRPORTS(IATA_CODE)
    , CONSTRAINT FK_FLIGHTS_KEY_DESTINATION_AIRPORTS FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES PH_DATA.NORTHWOODS.AIRPORTS(IATA_CODE)
    , CONSTRAINT FK_FLIGHTS_CANCELLED_REASON FOREIGN KEY (CANCELLATION_REASON) REFERENCES PH_DATA.NORTHWOODS.CANCEL_REASON_CODE(cancel_code)
            
);
